[tool.ruff]
line-length = 100
target-version = "py312"

exclude = [
    "__pycache__",
    ".git",
    ".idea",
    ".venv",
    ".venv_dev",
]

[tool.ruff.lint]
select = ["ALL"]

ignore = [
    "B017",
    "B901",
    "COM812",
    "CPY",
    "D",
    "DOC",
    "ERA001",
    "FIX002",
    "G004",
    "NPY002",
    "PLR2004",
    "PTH123",
    "S311",
    "T201",
    "TD",
    "TID252",
    "UP038",
]

[tool.ruff.lint.isort]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder"
]

[tool.ruff.lint.pylint]
max-args = 10
max-positional-args = 7
